import { writeFile, mkdir } from 'node:fs/promises'
import { join } from 'node:path'

/**
 * Generate transparent command wrapper scripts in .vibe/bin/
 * These scripts proxy commands into the Docker container so the candidate
 * can use `npm test`, `python`, etc. without knowing about Docker.
 */
export async function generateWrapperScripts(
  workspacePath: string,
  commands: string[],
  sessionId: string,
): Promise<void> {
  const binDir = join(workspacePath, '.vibe', 'bin')
  await mkdir(binDir, { recursive: true })

  const containerName = `vibe-${sessionId}`

  // Generate a wrapper for each command
  for (const cmd of commands) {
    const script = createWrapperScript(containerName, cmd)
    const scriptPath = join(binDir, cmd)
    await writeFile(scriptPath, script, { mode: 0o755 })
  }

  // Generate catch-all vibe-exec wrapper
  const vibeExec = createVibeExecScript(containerName)
  const vibeExecPath = join(binDir, 'vibe-exec')
  await writeFile(vibeExecPath, vibeExec, { mode: 0o755 })

  // Generate a .env file that prepends .vibe/bin to PATH
  const envScript = `#!/bin/bash\nexport PATH="${binDir}:$PATH"\nexport VIBE_CONTAINER="${containerName}"\n`
  await writeFile(join(workspacePath, '.vibe', 'env.sh'), envScript, { mode: 0o755 })
}

function createWrapperScript(containerName: string, command: string): string {
  return `#!/bin/bash
# Auto-generated by vibe-interviewing
# Transparently runs '${command}' inside the interview Docker container
exec docker exec -i "${containerName}" ${command} "$@"
`
}

function createVibeExecScript(containerName: string): string {
  return `#!/bin/bash
# Auto-generated by vibe-interviewing
# Runs arbitrary commands inside the interview Docker container
if [ $# -eq 0 ]; then
  echo "Usage: vibe-exec <command> [args...]"
  exit 1
fi
exec docker exec -i "${containerName}" "$@"
`
}
